# Generated by Django 5.0.9 on 2024-11-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(choices=[('250g', '۲۵۰ گرم'), ('500g', 'نیم کیلو'), ('1000g', 'یک کیلو')], max_length=10, verbose_name='وزن')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='قیمت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='product.product', verbose_name='محصول')),
            ],
        ),
    ]
