# Generated by Django 5.0.9 on 2024-11-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AlterField(
            model_name='productweight',
            name='weight',
            field=models.CharField(max_length=10, verbose_name='وزن'),
        ),
    ]
