# Generated by Django 5.0.9 on 2024-10-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد مرجع پرداخت')),
                ('status', models.CharField(choices=[('initiated', 'در انتظار'), ('successful', 'موفق'), ('failed', 'خطا'), ('canceled', 'کنسل شده')], default='initiated', max_length=20, verbose_name='وضعیت پرداخت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
    ]
